### ISSUE TITLE
v3.0.1 compatibility with React < v18.0.0

### ISSUE THREAD

**Issue by josephcyrus-valtech** [nerdyman/react-compare-slider#125]
Is v3.0.1 compatible with React v17.0.2? 

The docs state React v16.8+ is required, but I get the following server error.

Code
```
import { ReactCompareSlider, ReactCompareSliderImage } from 'react-compare-slider';

export const Example = () => {
  return (
    <ReactCompareSlider
      itemOne={<ReactCompareSliderImage src="..." srcSet="..." alt="Image one" />}
      itemTwo={<ReactCompareSliderImage src="..." srcSet="..." alt="Image two" />}
    />
  );
};
```

Server Error
```
Error: Cannot find module '.../node_modules/react/jsx-runtime' imported from ...node_modules/react-compare-slider/dist/index.mjs
Did you mean to import react/jsx-runtime.js?
```

Versions
```
"react": "^17.0.2",
"react-compare-slider": "^3.0.1",
"react-dom": "^17.0.2",
```

Worth noting, when reverting to v2.2.0, it works with React v17.0.2.
